### ISSUE TITLE
请问这工具叫什么

### ISSUE THREAD

**Issue by OCDpunk** [SecWiki/CMS-Hunter#4]
![image](https://user-images.githubusercontent.com/18011687/56259383-65133880-6105-11e9-8aa4-b99a6aae4794.png)

**Comment by ttttmr** [comment]
应该是hackbar

**Comment by OCDpunk** [comment]
> 应该是hackbar

在chrome 网上应用店 搜了下 好像不太像

**Comment by ourren** [comment]
这是 Firefox 下的 hackbar

**Comment by zprogram** [comment]
hackerbar 增强版
